stages:
  - bake
default:
  retry:
    max: 1
    when:
      - unknown_failure
      - api_failure
      - stuck_or_timeout_failure
      - runner_system_failure
      - runner_unsupported
      - stale_schedule
      - job_execution_timeout
      - unmet_prerequisites
      - scheduler_failure
      - data_integrity_failure


variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: 1
  IMAGE_TAG_NAME: ${CI_COMMIT_REF_SLUG}
  CACHE_IMAGE: ${CI_REGISTRY_IMAGE}/cache

bake:
  stage: bake
  image: docker
  services:
    - name: docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cp .env.dist .env
  script:
    # TODO: push the final image and add more customzation
    - docker buildx bake --set *.cache-to=type=registry,ref=${CACHE_IMAGE},mode=max --set *.cache-from=type=registry,ref=${CACHE_IMAGE} -f ${COMPOSE_FILE} -f ${COMPOSE_OVERRIDE_FILE}
  rules:
    - when: always